services:
    imcger.participantslist.ptsl_acp_listener:
        class: imcger\participantslist\event\ptsl_acp_listener
        tags:
            - { name: event.listener }
            
    imcger.participantslist.ptsl_main_listener:
        class: imcger\participantslist\event\ptsl_main_listener
        arguments:
            - '@user'
            - '@auth'
            - '@language'
            - '@template'
            - '@dbal.conn'
            - '@request'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
        tags:
            - { name: event.listener }
            
    imcger.participantslist.ptsl_list_controller:
        class: imcger\participantslist\controller\ptsl_list_controller
        arguments:
            - '@controller.helper'
            - '@user'
            - '@auth'
            - '@language'
            - '@template'
            - '@dbal.conn'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
